config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :veterinarians
  resources :lizards
  resources :home
  resources :charts
  resources :clients


  root  'lizards#index'




end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :lizards, dependent: :destroy
end

app/models/lizard.rb
class Lizard < ActiveRecord::Base
   belongs_to :client
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/veterinarian.rb
class Veterinarian < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    @lizards  = Lizard.all
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    @clients = Client.all
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:first_name, :last_name, :phone_number, :address, :lizards_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @veterinarians = Veterinarian.all
  end
end

app/controllers/lizards_controller.rb
class LizardsController < ApplicationController
  before_action :set_lizard, only: [:show, :edit, :update, :destroy]

  def index
    @lizards = Lizard.all
  end

  def show
  end

  def new
    @lizard = Lizard.new
  end

  def edit
  end

  def create
    @lizard = Lizard.new(lizard_params)

    respond_to do |format|
      if @lizard.save
        format.html { redirect_to @lizard, notice: 'Lizard was successfully created.' }
        format.json { render :show, status: :created, location: @lizard }
      else
        format.html { render :new }
        format.json { render json: @lizard.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @lizard.update(lizard_params)
        format.html { redirect_to @lizard, notice: 'Lizard was successfully updated.' }
        format.json { render :show, status: :ok, location: @lizard }
      else
        format.html { render :edit }
        format.json { render json: @lizard.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lizard.destroy
    respond_to do |format|
      format.html { redirect_to lizards_url, notice: 'Lizard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def set_lizard
    @lizard = Lizard.find(params[:id])
  end

  def lizard_params
    params.require(:lizard).permit(:petname, :weight, :length, :social_score, :diet_score, :fitness_score, :mental_score, :last_seen)
  end
end

app/controllers/users_controller.rb
class UsersController  < ApplicationController

  def index
    @users = User.all
  end
end

app/controllers/veterinarians_controller.rb
class VeterinariansController < ApplicationController
  before_action :set_veterinarian, only: [:show, :edit, :update, :destroy]


  def index
    @veterinarians = Veterinarian.all
  end

  def show
  end

  def new
    @veterinarian = Veterinarian.new
  end

  def edit
  end

  def create
    @veterinarian= Veterinarian.new(veterinarian_params)

    respond_to do |format|
      if @veterinarian.save
        format.html { redirect_to @veterinarian, notice: 'Veterinarian was successfully created.' }
        format.json { render :show, status: :created, location: @veterinarian }
      else
        format.html { render :new }
        format.json { render json: @veterinarian.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @veterinarian.update(veterinarian_params)
        format.html { redirect_to @veterinarian, notice: 'Veterinarian was successfully updated.' }
        format.json { render :show, status: :ok, location: @veterinarian }
      else
        format.html { render :edit }
        format.json { render json: @veterinarian.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @veterinarian.destroy
    respond_to do |format|
      format.html { redirect_to veterinarians_url, notice: 'Veterinarian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def set_veterinarian
    @veterinarian = Veterinarian.find(params[:id])
  end

  def veterinarian_params
    params.require(:veterinarian).permit(:first_name, :last_name, :years_in_practice, :vet_university)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lizards_helper.rb
module LizardsHelper
end

app/helpers/veterinarians_helper.rb
module VeterinariansHelper
end

app/views/charts/index.html.erb
<div class='row'>
  <%= render 'lizards/sidebar' %>
    <div class='col-6 col-m-9'>
    <h1>Practice Performance Analytics</h1>
    <h2>Getting Pets in for visits</h2>
      <div class='chart'>
      <%= area_chart @lizards.group_by_month(:last_seen).count %>
      </div>

      <h2>Avg Social Score</h2>
      <div class='chart'>
      <%= line_chart Lizard.group(:social_score).count %>
      </div>

      <h2>Avg Diet Score</h2>
      <div class='chart'>
      <%= bar_chart @lizards.group(:diet_score).count %>
      </div>

      <h2>Avg Fitness Score</h2>
      <div class='chart'>
      <%= pie_chart @lizards.group(:fitness_score).count %>
      </div>

      <h2>Avg Mental Score</h2>
      <div class='chart'>
      <%= column_chart @lizards.group(:mental_score).count %>
      </div>
  </div>
  </div>
</div>

app/views/clients/_form.html.erb
<div class="smoothScroll">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= form_for(@client) do |f| %>
    <% if @client.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@client.errors.count, "error") %> prohibited this lizard from being saved:</h2>

        <ul>
        <% @client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name%><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :phone_number %><br>
      <%= f.text_field :phone_number %>
    </div>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label "Lizards ID"%><br>
      <%= f.text_field :lizards_id %>
    </div>
    <div class="actions">
      <%= f.submit 'Submit' %>
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class='main'>
  <h1>Edit Client</h1>

  <%= render 'form' %>

  <%= link_to 'Back', lizards_path %>
</div>

app/views/clients/index.html.erb
<div class='row'>
  <%= render 'lizards/sidebar' %>
    <div class='col-6 col-m-9'>
      <p id="notice"><%= notice %></p>
    <h1>Pet Owners</h1>
    <table>
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Phone Number</th>
          <th>Address</th>
          <th>Pet Name</th>
          <th>Manage</th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |client| %>
        <tr>
          <td><%= client.first_name %></td>
          <td><%= client.last_name %></td>
          <td><%= client.phone_number %></td>
          <td><%= client.address %></td>
          <td><%= client.lizards_id%></td>
          <td><%= link_to 'Edit', edit_client_path(client) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'New client', new_client_path %> | <%= link_to 'Back', lizards_path %>
  </div>
</div>

app/views/clients/new.html.erb
<div class='main'>
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', lizards_path %>
</div>

app/views/clients/show.html.erb
<div class='main'>
  <p id="notice"><%= notice %>
    
    <strong>First Name:</strong>
    <%= @client.first_name %>

    <strong>Last Name:</strong>
    <%= @client.last_name %>

    <strong>Phone Number:</strong>
    <%= @client.phone_number %>

    <strong>Address:</strong>
    <%= @client.address %>

    <strong>Lizard ID</strong>
    <%= @client.lizards_id %>
  <%= link_to 'Edit', edit_client_path(@client) %> |
  <%= link_to 'Back', clients_path %>
</div>

app/views/home/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<div class="content">
  <div class="intro">
    <h1>The Veternarians</h1>
    <h2>We are in the business of caring for your pet through analytics to help them live their best lives</h2>
      <%= image_tag("dog_riding_in_the_car.jpg", :alt => "dog out of window") %>
  </div>
  <div class="analytics">
    <h2> How do we use analytics?</h2>
    <p> We gather information from visits with your pet and chart using a patented formula ways you can improve the life of your beloved family member. </p>
    <p> Using our state of the art algoritum for predicting where you pet needs to focus
      to improve health. Whether that is with a balanced diet or more walks with you<p>
    <h3>Here are the 4 points of your pets life we track</h3>
      <ul>
        <li>Diet</li>
        <li>Mental Health</li>
        <li>Social aptitude</li>
        <li>Fitness</li>
      </ul>
    <p>
  <div>
</div>

app/views/layouts/_footer.html.erb
<% if 1==1 %>
<% else %>
  <div class='contact'>
    <p>Contact Us!</p></br>
    <p>The Veterinarians</p></br>
    <p>129999 Fluffy Way, </p>
    <p>Arlington, VA 22320</p>
    <p>o: 703-555-5555</p> |
    <p>f: 708-555-8888</p>
  </div>
  <div class='social-media'>
    <h4>Connect with us on Social Media!</h4>
    <i class="fa fa-facebook-square fa-3x" aria-hidden="true"><%=link_to '', '#' %></i>
    <i class="fa fa-twitter-square fa-3x" aria-hidden="true"><%=link_to '', '#' %></i>
    <i class="fa fa-youtube-square fa-3x" aria-hidden="true"><%=link_to '', '#' %></i>
  </div>
<%end%>

app/views/layouts/_nav.html.erb
<div class='header'>
<% if 1==1 %>
  <h1>The Veterinarians Internal Portal </h1>
<% else %>
  <%= link_to "Login",  user_session_path %>
  <%= link_to "Home", home_index_path%>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://use.fontawesome.com/8795c4ff26.js"></script>
  <title>The Vet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "path/to/highcharts.js", "chartkick" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%=render "layouts/nav"%>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
<div class='footer'><%= render "layouts/footer" %></div>
</html>

app/views/lizards/_form.html.erb
<div class="smoothScroll">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= form_for(@lizard) do |f| %>
  <% if @lizard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lizard.errors.count, "error") %> prohibited this lizard from being saved:</h2>

      <ul>
      <% @lizard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :petname %><br>
    <%= f.text_field :petname %>
  </div>
  <div class="field">
    <%= f.label :weight %>(lbs)<br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :length %>(ins)<br>
    <%= f.text_field :length %>
  </div>
  <div  class="field">
    <%= f.label :social_score %><br>
    <%= f.text_field :social_score %>
  </div>
  <div class="field">
    <%= f.label :diet_score %><br>
    <%= f.text_field :diet_score %>
  </div>
  <div class="field">
    <%= f.label :fitness_score%><br>
    <%= f.text_field :fitness_score %>
  </div>
  <div class="field">
    <%= f.label :mental_score %><br>
    <%= f.text_field :mental_score %>
  </div>
  <div class="field">
    <%= f.label :last_seen %><br>
    <%= f.date_select :last_seen %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
</div>
<% end %>

app/views/lizards/_sidebar.html.erb
<div class='col-3 col-m-12 menu'>
  <div class='main'>
  <ul>
    <li><%= link_to 'Case Load', lizards_path %></li>
    <li><%= link_to 'Analytics',charts_path %></li>
    <li><%= link_to 'Clients',clients_path %></li>
    <li><%= link_to 'Manage Vets', veterinarians_path%></li>
  </ul>
  </div>
</div>

app/views/lizards/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @lizard %> |
<%= link_to 'Back', lizards_path %>

app/views/lizards/index.html.erb
<div class='row'>
  <%= render 'lizards/sidebar' %>
  <div class='col-6 col-m-9'>
  <p id="notice"><%= notice %></p>
  <h1>Case Load</h1>
  <table>
    <thead>
      <tr>
        <th><strong>ID</strong></th>
        <th><strong>Pet Name</strong></th>
        <th>Weight</th>
        <th>Length</th>
        <th>Social Score</th>
        <th>Diet Score</th>
        <th>Fitness Score</th>
        <th>Mental Score</th>
        <th>Last seen</th>
        <th>Manage</th>
      </tr>
    </thead>
    <tbody>
      <% @lizards.each do |lizard| %>
      <tr>
        <td><%= lizard.id %></td>
        <td><%= lizard.petname %></td>
        <td><%= lizard.weight %></td>
        <td><%= lizard.length %></td>
        <td><%= lizard.social_score %></td>
        <td><%= lizard.diet_score %></td>
        <td><%= lizard.fitness_score %></td>
        <td><%= lizard.mental_score %></td>
        <td><%= lizard.last_seen.strftime("%m/%d/%Y") %></td>
        <td><%= link_to 'Edit', edit_lizard_path(lizard) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Pet', new_lizard_path %>
  </div>
</div>

app/views/lizards/new.html.erb
<div class='main'>
  <h1>New Pet</h1>

  <%= render 'form' %>

  <%= link_to 'Back', lizards_path %>
</div>

app/views/lizards/show.html.erb
<div class='main'>
  <p id="notice"><%= notice %>
    <strong>ID:</strong>
    <%= @lizard.id %>

    <strong>Petname:</strong>
    <%= @lizard.petname %>

    <strong>Weight:</strong>
    <%= @lizard.weight %>

    <strong>Length:</strong>
    <%= @lizard.length %>

    <strong>Social Score:</strong>
    <%= @lizard.social_score %>

    <strong>Diet Score:</strong>
    <%= @lizard.diet_score %>

    <strong>Fitness Score:</strong>
    <%= @lizard.fitness_score %>

    <strong>Mental Score:</strong>
    <%= @lizard.mental_score %>

    <strong>Last seen:</strong>
    <%= @lizard.last_seen %>

  <%= link_to 'Edit', edit_lizard_path(@lizard) %> |
  <%= link_to 'Back', lizards_path %>
</div>

app/views/users/index.html.erb
users index

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<% if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/veterinarians/_form.html.erb
<%= form_for(@veterinarian) do |f| %>
  <% if @veterinarian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@veterinarian.errors.count, "error") %> prohibited this lizard from being saved:</h2>
      <ul>
      <% @veterinarian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :years_in_practice %><br>
    <%= f.text_field :years_in_practice %>
  </div>
  <div class="field">
    <%= f.label :vet_university %><br>
    <%= f.text_field :vet_university %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/veterinarians/edit.html.erb
<h1>Editing Veterinarian</h1>

<%= render 'form' %>

<%= link_to 'Show', @veterinarian %> |
<%= link_to 'Back', veterinarians_path %>

app/views/veterinarians/index.html.erb
<div class='row'>
  <%= render 'lizards/sidebar' %>
    <div class='col-6 col-m-9'>
    <p id="notice"><%= notice %></p>
    <h1>Practice Veterinarians</h1>
    <table>
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>Years in practice</th>
          <th>Vet university</th>
          <th colspan="3">Manage</th>
        </tr>
      </thead>
      <tbody>
        <% @veterinarians.each do |veterinarian| %>
          <tr>
            <td><%= veterinarian.first_name %></td>
            <td><%= veterinarian.last_name %></td>
            <td><%= veterinarian.years_in_practice %></td>
            <td><%= veterinarian.vet_university %></td>
            <td><%= link_to 'Edit', edit_veterinarian_path(veterinarian) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'New Veterinarian', new_veterinarian_path %> | <%= link_to 'Back', lizards_path %>
  </div>
</div>

app/views/veterinarians/new.html.erb
<h1>New Veterinarian</h1>

<%= render 'form' %>

<%= link_to 'Back', veterinarians_path %>

app/views/veterinarians/show.html.erb
<div class='main'>
  <p id="notice"><%= notice %>
    <strong>First Name:</strong>
    <%= @veterinarian.first_name %>

    <strong>Last Name:</strong>
    <%= @veterinarian.last_name %>

    <strong>Years in Practice:</strong>
    <%=  @veterinarian.years_in_practice %>

    <strong>Vet University:</strong>
    <%= @veterinarian.vet_university %>

  <%= link_to 'Edit', edit_client_path(@veterinarian) %> |
  <%= link_to 'Back', clients_path %>
</div>